openimis/openimis-fe-individual_js

- .eslintrc.json
- .github/workflows/CI_and_build copy.yml
- .github/workflows/eslint_check.yml
- package.json
- src/actions.js
- src/components/IndividualFilter.js
- src/components/IndividualHeadPanel.js
- src/components/IndividualSearcher.js
- src/constants.js
- src/index.js
- src/menus/BeneficiaryMainMenu.js
- src/pages/IndividualPage.js
- src/pages/IndividualsPage.js
- src/reducer.js
- src/util/action-type.js
- src/util/json-validate.js
- src/util/styles.js
TICKET: [CM-116](https://openimis.atlassian.net/browse/CM-116)
[CM-116]: https://openimis.atlassian.net/browse/CM-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CM-116: Added eslint and fixed workflow

- src/actions.js
- src/components/GroupFilter.js
- src/components/GroupHeadPanel.js
- src/components/GroupSearcher.js
- src/components/IndividualFilter.js
- src/components/IndividualSearcher.js
- src/reducer.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-121
> CM-121: address QA points

- src/components/GroupSearcher.js
- src/components/IndividualSearcher.js
- src/reducer.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-105
https://openimis.atlassian.net/browse/CM-29
> CM-105: fix downloads

- src/components/BenefitPlansListTab.js
[CM-217](https://openimis.atlassian.net/browse/CM-217)
[RELATED PR](https://github.com/openimis/openimis-fe-social_protection_js/pull/36)
Changes:
- Use a specialized Searcher specifically dedicated to beneficiaries and group beneficiaries.
[CM-217]: https://openimis.atlassian.net/browse/CM-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CM-217: use searcher for individuals/groups

- src/actions.js
- src/components/GroupIndividualSearcher.js
- src/components/GroupSearcher.js
- src/components/IndividualSearcher.js
- src/index.js
- src/reducer.js
- src/util/action-type.js
https://openimis.atlassian.net/browse/CM-158
This PR fixes bug with downloading when switching tabs.
> CM-158: fix download and switching tabs

- src/actions.js
- src/components/GroupSearcher.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-295
This PR will display head of group in searcher.
It needs: https://github.com/openimis/openimis-be-individual_py/pull/24
> CM-295: display group head

- src/components/GroupSearcher.js
- src/components/IndividualSearcher.js
- src/constants.js
- src/util/searcher-utils.js
https://openimis.atlassian.net/browse/CM-296
This pr adds ability to use custom filters for groups and individuals.
It needs: https://github.com/openimis/openimis-fe-core_js/pull/162
> CM-296: add custom filtering to individuals and groups

- src/components/tasks/IndividualUpdateTasks.js
- src/index.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-380
It needs:
https://github.com/openimis/openimis-be-individual_py/pull/33
> CM-380: add update individual task table

- src/actions.js
- src/components/GroupChangelogTab.js
- src/components/GroupHistoryFilter.js
- src/components/GroupHistorySearcher.js
- src/constants.js
- src/index.js
- src/reducer.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-406
It needs: https://github.com/openimis/openimis-be-individual_py/pull/35
> CM-406: add change log fe for group

- src/actions.js
- src/components/IndividualChangelogTab.js
- src/components/IndividualHistoryFilter.js
- src/components/IndividualHistorySearcher.js
- src/constants.js
- src/index.js
- src/reducer.js
- src/translations/en.json
TICKET: https://openimis.atlassian.net/browse/CM-381
> CM-381: Create change log tab for individual

- src/components/GroupChangeDialog.js
- src/components/GroupIndividualSearcher.js
- src/pickers/GroupPicker.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-404
It needs: https://github.com/openimis/openimis-be-individual_py/pull/37
> CM-404: move individual to another group

- src/components/GroupChangeDialog.js
- src/components/GroupIndividualSearcher.js
- src/components/tasks/GroupIndividualUpdateTasks.js
- src/index.js
- src/pickers/GroupPicker.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-405
It needs: https://github.com/openimis/openimis-be-individual_py/pull/40
> CM-405: add tasks on frontend

- src/components/GroupChangeDialog.js
- src/components/GroupHistorySearcher.js
- src/components/GroupIndividualSearcher.js
- src/components/tasks/GroupIndividualUpdateTasks.js
- src/index.js
- src/pickers/GroupPicker.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-408
It displays members in change log.
It needs: https://github.com/openimis/openimis-be-individual_py/pull/41
> CM-408: display members in task

- src/actions.js
- src/components/GroupHistorySearcher.js
- src/components/IndividualHistorySearcher.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-406
It needs: https://github.com/openimis/openimis-be-individual_py/pull/44
> CM-406: add user updated

- src/components/GroupHistoryFilter.js
- src/components/IndividualHistoryFilter.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-406
It needs: https://github.com/openimis/openimis-be-individual_py/pull/48
> CM-406: add new filters for history

- src/components/GroupTaskTab.js
- src/components/IndividualTaskTab.js
- src/constants.js
- src/index.js
- src/translations/en.json
> CM-396: added Tasks tab for Individual and Group

- src/actions.js
- src/components/GroupChangeDialog.js
- src/components/GroupHeadPanel.js
- src/components/GroupIndividualSearcher.js
- src/components/IndividualTabPanel.js
- src/components/IndividualsListTab.js
- src/components/tasks/GroupCreateTasks.js
- src/components/tasks/GroupIndividualUpdateTasks.js
- src/index.js
- src/pages/GroupPage.js
- src/reducer.js
- src/translations/en.json
- src/util/action-type.js
This ticket needs to be on done: https://openimis.atlassian.net/browse/CM-473
And it needs this PR: https://github.com/openimis/openimis-be-individual_py/pull/50
> CM-465: move individual to new group

- src/components/tasks/GroupCreateTasks.js
https://openimis.atlassian.net/browse/CM-458
It adjust create new group task display to new backend from this PR: https://github.com/openimis/openimis-be-tasks_management_py/pull/37
> CM-458: adjust group create task display

- src/components/GroupSearcher.js
- src/components/IndividualSearcher.js
- src/constants.js
https://openimis.atlassian.net/browse/CM-501
It needs: https://github.com/openimis/openimis-be-individual_py/pull/55
> CM-501: adjust frontend to individual custom filters

- src/actions.js
- src/components/CollapsableErrorList.js
- src/components/dialogs/AdvancedCriteriaForm.js
- src/components/dialogs/IndividualsHistoryUploadDialog.js
- src/components/dialogs/IndividualsUploadDialog.js
- src/constants.js
- src/reducer.js
- src/translations/en.json
- src/utils.js
TICKET: https://openimis.atlassian.net/browse/CM-729
> CM-729: added individual upload history dialog

- src/components/EnrollmentHeadPanel.js
- src/components/dialogs/AdvancedCriteriaForm.js
- src/index.js
https://openimis.atlassian.net/browse/CM-737
> CM-737: make AppliedCriteriaRow public reference

- src/actions.js
- src/components/GroupIndividualHistoryFilter.js
- src/components/GroupIndividualHistorySearcher.js
- src/components/GroupIndividualHistoryTab.js
- src/components/GroupTabPanel.js
- src/constants.js
- src/index.js
- src/pages/GroupPage.js
- src/reducer.js
- src/translations/en.json
TICKET: https://openimis.atlassian.net/browse/CM-717
> CM-717: As an auditor I want to have clear information about the groups individual belonged to

- src/components/dialogs/IndividualsHistoryUploadDialog.js
- src/components/dialogs/IndividualsUploadDialog.js
- src/translations/en.json
- src/utils.js
https://openimis.atlassian.net/browse/CM-700
It needs: https://github.com/openimis/openimis-fe-core_js/pull/207 and https://github.com/openimis/openimis-be-individual_py/pull/68
> CM-700: download upload file

- src/pickers/WorkflowsPicker.js
https://openimis.atlassian.net/browse/CM-726
> CM-726: added changes in picker workflow

- src/actions.js
- src/pickers/WorkflowsPicker.js
https://openimis.atlassian.net/browse/CM-726
> CM-726: Added filters for workflow

- src/components/GroupIndividualSearcher.js
- src/components/GroupTabPanel.js
- src/components/IndividualsListTab.js
- src/components/dialogs/IndividualsHistoryUploadDialog.js
- src/pages/GroupPage.js
https://openimis.atlassian.net/browse/CM-847
> CM-847: fix droup id passing via prop

- src/components/dialogs/IndividualsHistoryUploadDialog.js
TICKET: https://openimis.atlassian.net/browse/CM-741
> CM-741: fixed height of history upload modal

- src/components/dialogs/IndividualsHistoryUploadDialog.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-688
> CM-742: update history upload frontend

- src/components/GroupIndividualSearcher.js
- src/components/GroupSearcher.js
- src/components/IndividualSearcher.js
[OP-1468](https://openimis.atlassian.net/browse/OP-1468)
Changes:
- Improve error handling for export failures. Currently, a pop-up message is displayed from the backend.
[OP-1468]: https://openimis.atlassian.net/browse/OP-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1468: fix handling failed export

- src/actions.js
- src/components/GroupIndividualFilter.js
- src/components/GroupIndividualSearcher.js
- src/components/IndividualFilter.js
- src/components/IndividualSearcher.js
- src/components/tasks/IndividualTasks.js
- src/index.js
- src/pages/IndividualPage.js
- src/reducer.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-879
It needs:
https://github.com/openimis/openimis-be-individual_py/pull/81
> CM-879: add undo delete individual

- src/actions.js
- src/components/GroupFilter.js
- src/components/GroupHeadPanel.js
- src/components/GroupSearcher.js
- src/components/dialogs/IndividualsUploadDialog.js
- src/translations/en.json
https://openimis.atlassian.net/browse/CM-809
> CM-809: update group_code

- src/actions.js
- src/components/EnrollmentGroupHeadPanel.js
- src/components/GroupSearcher.js
- src/components/dialogs/AdvancedCriteriaGroupForm.js
- src/components/dialogs/GroupMenu.js
- src/components/dialogs/GroupPreviewEnrollmentDialog.js
- src/constants.js
- src/index.js
- src/pages/EnrollmentGroupPage.js
- src/pages/GroupsPage.js
- src/reducer.js
- src/translations/en.json
> CM-812: Added enrollment for group

- src/actions.js
- src/components/dialogs/IndividualAddToGroupDialog.js
- src/pages/GroupPage.js
- src/pickers/IndividualAddToGroupPicker.js
- src/reducer.js
- src/translations/en.json
TICKET: https://openimis.atlassian.net/browse/CM-842
> CM-842: feature to add individuals to group om group page

- src/components/IndividualSearcher.js
TICKET: https://openimis.atlassian.net/browse/CM-925
> CM-925: enroll indviduals which are not attached to any group

- src/actions.js
- src/components/BenefitsGroupTab.js
- src/index.js
TICKET: https://openimis.atlassian.net/browse/CM-919
> CM-919: added benefit tab for group
